add banner to readme
WFCD/Warframe.js pull request #3
Opened 2021-12-23 18:40 UTC by lucakiebel

### What did you fix? (provide a description or issue closes statement)

added banner to readme.md

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Have I run the linter? **[No]**
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**

2021-12-24 05:16 UTC, TobiTenno commented
you'll need to submit a PR to WFCD/banner first

2021-12-24 05:18 UTC, TobiTenno commented
also, typically just do either badge or banner, not both :D

2021-12-24 10:55 UTC, lucakiebel commented
The usage guide on the banner repo is a little misleading there:

> To use the banner, please submit a pull request to this repository adding an entry to PROJECTS.md, providing proof that you are using the below snippet in your readme appropriately.

I can't proof that I am using the banner in my readme without putting it in there first 😅😅😅

2021-12-24 14:22 UTC, TobiTenno commented
Ok, sure, either way... You only need one or the other, but both banner and badge

2021-12-25 00:52 UTC, TobiTenno requested changes

2021-12-25 00:52 UTC, TobiTenno commented on README.md
> +[![Supported by Warframe Community Developers](https://warframestat.us/wfcd.png)](https://github.com/WFCD "Supported by Warframe Community Developers")
```suggestion
```

2021-12-25 01:10 UTC, TobiTenno approved these changes

2021-12-25 01:10 UTC, merged